/**
 * Lightweight PDB file parser.
 *
 * Extracts atoms, residues, chains, and backbone (CA–CA) bonds from a PDB
 * text string. Used by the three.js-based 3D molecular viewer
 * (`pdb-3d-viewer.tsx`).
 *
 * Reference (column indices are 0-based):
 *   ATOM      1  CA  ALA A   1       0.000   0.000   0.000  1.00 20.00           C
 *   0         1         2         3         4         5         6         7
 *   0123456789012345678901234567890123456789012345678901234567890123456789012345678
 *   |______| |______| |____| |_| |____| |____________| |____________| |____|
 *    recName serial  name res ch resSeq      x,y,z       occ,bfac   element
 */

export interface PdbAtom {
  serial: number;
  name: string;
  element: string;
  x: number;
  y: number;
  z: number;
  resName: string;
  resSeq: number;
  chainId: string;
  bfactor: number;
  isHetero: boolean;
}

export interface PdbStructure {
  atoms: PdbAtom[];
  chains: string[];
  residueCount: number;
  title: string;
  /** CA–CA backbone bonds (indices into `atoms`). */
  backboneBonds: [number, number][];
}

/** Parse a PDB text string into a structure. */
export function parsePdb(text: string): PdbStructure {
  const atoms: PdbAtom[] = [];
  let title = "";
  const chainSet = new Set<string>();
  const residueSet = new Set<string>();

  for (const line of text.split("\n")) {
    const rec = line.slice(0, 6).trim();
    if (rec === "ATOM" || rec === "HETATM") {
      const isHetero = rec === "HETATM";
      const name = line.slice(12, 16).trim();
      const resName = line.slice(17, 20).trim();
      const chainId = line[21] || "A";
      const resSeq = parseInt(line.slice(22, 26), 10) || 0;
      const x = parseFloat(line.slice(30, 38)) || 0;
      const y = parseFloat(line.slice(38, 46)) || 0;
      const z = parseFloat(line.slice(46, 54)) || 0;
      let element = line.slice(76, 78).trim().toUpperCase();
      if (!element) {
        // Infer from atom name (first letter, or first 2 if lowercase second).
        element = name[0] || "C";
        if (
          name.length > 1 &&
          name[1] === name[1].toLowerCase() &&
          name[1] !== name[1].toUpperCase()
        ) {
          element = name.slice(0, 2);
        }
      }
      const bfactor = parseFloat(line.slice(60, 66)) || 0;
      atoms.push({
        serial: atoms.length + 1,
        name,
        element,
        x,
        y,
        z,
        resName,
        resSeq,
        chainId,
        bfactor,
        isHetero,
      });
      chainSet.add(chainId);
      residueSet.add(`${chainId}:${resSeq}`);
    } else if (rec === "TITLE") {
      title += line.slice(10).trim() + " ";
    }
  }

  // Build backbone bonds (CA–CA within the same chain).
  const backboneBonds: [number, number][] = [];
  const caByChain = new Map<string, { idx: number; resSeq: number }[]>();
  atoms.forEach((atom, idx) => {
    if (atom.name === "CA") {
      const arr = caByChain.get(atom.chainId) ?? [];
      arr.push({ idx, resSeq: atom.resSeq });
      caByChain.set(atom.chainId, arr);
    }
  });
  for (const arr of caByChain.values()) {
    arr.sort((a, b) => a.resSeq - b.resSeq);
    for (let i = 1; i < arr.length; i++) {
      if (arr[i].resSeq - arr[i - 1].resSeq <= 1) {
        backboneBonds.push([arr[i - 1].idx, arr[i].idx]);
      }
    }
  }

  return {
    atoms,
    chains: Array.from(chainSet).sort(),
    residueCount: residueSet.size,
    title: title.trim() || "Untitled structure",
    backboneBonds,
  };
}

/** Generate a sample PDB (24-residue helix) for demo purposes. */
export function generateSamplePdb(): string {
  const lines: string[] = ["REMARK   1 GENERATED BY FOUNDRY-LAB (SAMPLE)"];
  for (let i = 1; i <= 24; i++) {
    const t = i * 0.6;
    const x = (15 * Math.cos(t)).toFixed(3);
    const y = (3 * t).toFixed(3);
    const z = (15 * Math.sin(t)).toFixed(3);
    lines.push(
      `ATOM  ${String(i).padStart(5)}  CA  ALA A${String(i).padStart(4)}     ${x.padStart(8)} ${y.padStart(8)} ${z.padStart(8)}  1.00 20.00           C`,
    );
  }
  lines.push("END");
  return lines.join("\n");
}
