// GET /api/tools/jobs/[id]/file
//   - If `?path=<file>` is NOT provided → return the simulated `outputFiles`
//     list as JSON so clients can discover what's available.
//   - If `?path=<file>` IS provided → generate + return the file's content.
//     PDB → chemical/x-pdb, FASTA → text/fasta, anything else falls back to
//     the job's stdout as text/plain.
//
// The content is generated on-the-fly from `simulateCompRun` + per-extension
// generators so the sandbox always has something realistic to hand back
// without storing real file artifacts.

import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import { getCompTool, simulateCompRun } from "@/lib/tools";

export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id } = await params;
  const job = await db.toolJob.findUnique({ where: { id } });
  if (!job) {
    return NextResponse.json({ error: "Job not found" }, { status: 404 });
  }

  const tool = getCompTool(job.tool);
  if (!tool) {
    return NextResponse.json({ error: "Unknown tool" }, { status: 400 });
  }

  // Parse the stored params (note: renamed to `parsedParams` to avoid
  // shadowing the route-handler `params` arg).
  let parsedParams: Record<string, unknown> = {};
  try {
    const raw = JSON.parse(job.params);
    if (raw && typeof raw === "object" && !Array.isArray(raw)) {
      parsedParams = raw as Record<string, unknown>;
    }
  } catch {
    /* ignore — fall back to empty params */
  }

  // Generate the simulated output (deterministic given seed + tool + params).
  const sim = simulateCompRun(tool, parsedParams);

  // Resolve the requested file path from the query string.
  const url = new URL(_request.url);
  const filePath = url.searchParams.get("path");

  if (!filePath) {
    // Return a list of files
    return NextResponse.json({ files: sim.outputFiles });
  }

  // Generate file content based on the file extension
  const fileName = filePath.split("/").pop() || "output";
  const ext = fileName.split(".").pop()?.toLowerCase();

  // The design index is the position of this path in the simulated list.
  // Fall back to 0 if not found so we always produce something.
  const designIndex = Math.max(0, sim.outputFiles.indexOf(filePath));

  let content = "";
  let contentType = "text/plain";

  if (ext === "pdb") {
    content = generatePdbContent(tool.key, parsedParams, designIndex);
    contentType = "chemical/x-pdb";
  } else if (ext === "fasta") {
    content = generateFastaContent(tool.key, parsedParams, designIndex);
    contentType = "text/fasta";
  } else {
    content = sim.stdout;
  }

  return new Response(content, {
    headers: {
      "Content-Type": contentType,
      "Content-Disposition": `inline; filename="${fileName}"`,
    },
  });
}

/**
 * Generate a deterministic PDB structure (a helix of CA atoms) for the given
 * tool / params / design index. The seed shifts per design so each design in
 * a multi-design run produces a slightly different backbone.
 */
function generatePdbContent(
  toolKey: string,
  params: Record<string, unknown>,
  designIndex: number,
): string {
  const lines: string[] = [];
  const numResidues = 24;
  const seed = Number(params.seed ?? 42) + designIndex * 7;
  for (let i = 1; i <= numResidues; i++) {
    const t = i * 0.6 + seed * 0.01;
    const x = (15 * Math.cos(t)).toFixed(3);
    const y = (3 * t).toFixed(3);
    const z = (15 * Math.sin(t)).toFixed(3);
    lines.push(
      `ATOM  ${String(i).padStart(5)}  CA  ALA A${String(i).padStart(4)}     ${x.padStart(8)} ${y.padStart(8)} ${z.padStart(8)}  1.00 20.00           C`,
    );
  }
  lines.push("END");
  // Include the tool key as a REMARK for traceability (PDB-aware viewers
  // ignore unknown record types, so this is harmless).
  return `REMARK   1 GENERATED BY FOUNDRY-LAB SIMULATION — tool=${toolKey} design=${designIndex + 1} seed=${seed}\n${lines.join("\n")}`;
}

/**
 * Generate a deterministic FASTA record (60 residues cycling through the 20
 * standard amino acids, offset by seed + seqIndex so each design differs).
 */
function generateFastaContent(
  toolKey: string,
  params: Record<string, unknown>,
  seqIndex: number,
): string {
  const seed = Number(params.seed ?? 42) + seqIndex * 13;
  const aas = "ACDEFGHIKLMNPQRSTVWY";
  const seq = Array.from(
    { length: 60 },
    (_, i) => aas[(seed + i) % 20],
  ).join("");
  return `>design_${seqIndex + 1}|${toolKey}|seed=${seed}\n${seq}\n`;
}
